const router = require("express").Router();
const UserController = require('../controller/user.controller');
router.post("/reg",UserController.register);
router.post("/login", UserController.login);
router.post("/resetPass", UserController.resetPass);
router.patch("/profile", UserController.updateUserProfile);
router.get("/profile", UserController.getUserProfile);
router.delete("/profile", UserController.deleteUser);
router.patch("/newPass", UserController.newPass);
router.post("/activate", UserController.updateActivation);
router.get('/users/search', UserController.searchUsers);
router.get('/all-children', UserController.getAllUsersWithRoleUser);
router.get('/all-children/search', UserController.searchUsersByName);
module.exports = router;